# Steps per Quarter definitions
STEPS_PER_QUARTER = [0.25, 0.5, 1, 2, 4, 8, 16, 32]

WHOLE_NOTE = SEMIBREVE = 0
HALF_NOTE = MINIM = 1
QUATER_NOTE = CROTCHET = 2
EIGTH_NOTE = QUAVER = 3
SIXTEENTH_NOTE = SEMIQUAVER = 4
THIRTY_SECOND_NOTE = DEMISEMIQUAVER = 5
SIXTY_FOURTH_NOTE = HEMIDEMISEMIQUAVER = 6
HUNDRED_TWENTY_EIGHT_NOTE = 7
NOTE_TYPE_MAX = HUNDRED_TWENTY_EIGHT_NOTE

# Tempo definitions
CHANGE_TIME = 0
TEMPO = 1
